export interface Workshop {
    id: string;
    contract_num: string;
    signup_num: string;
    fantasy_name: string;
    company_name: string;
    cnpj: string;
    contact: string;
    phone: string;
    website: string;
    email: string;
    state_code: string;
    city_code: string;
    cnae1: string;
    address: string;
    instagram: string;
    facebook: string;
    youtube: string;
    linkedin: string;
    twitter: string;
    others: string;
    is_branch: boolean;
    collaborators_amount: number;
    active_workers: number;
    avg_ticket: number;
    monthly_goal: number;
    revenue: number;
    clients: string[];
}